package de.ids_mannheim.korap.config;

import org.springframework.web.context.ContextLoaderListener;
import org.springframework.web.context.WebApplicationContext;

/**
 * A hack to inject the application context generated by
 * SpringJUnit4ClassRunner in the test suite.
 * 
 * @author margaretha
 *
 */
public class StaticContextLoaderListener extends ContextLoaderListener {

    public static WebApplicationContext applicationContext;

    public StaticContextLoaderListener () {
        super(applicationContext);
    }


}
