package de.ids_mannheim.korap.config;

/**
 * Created by hanl on 30.05.16.
 */
public class TestVariables {

    public static final String SIMPLE_ADD_QUERY = "[pos=ADJA]";

    public static final String RESULT = "{\n"
            + "\t\"@context\": \"http://korap.ids-mannheim.de/ns/KoralQuery/v0.3/context.jsonld\",\n"
            + "\t\"meta\": {\n"
            + "\t\t\"count\": 25,\n"
            + "\t\t\"startIndex\": 0,\n"
            + "\t\t\"timeout\": 120000,\n"
            + "\t\t\"context\": {\n"
            + "\t\t\t\"left\": [\"token\", 6],\n"
            + "\t\t\t\"right\": [\"token\", 6]\n"
            + "\t\t},\n"
            + "\t\t\"fields\": [\"pubDate\", \"subTitle\", \"author\", \"pubPlace\", \"title\", \"textSigle\", \"UID\", \"ID\", \"layerInfos\", \"corpusSigle\", \"docSigle\", \"corpusID\", \"textClass\"],\n"
            + "\t\t\"version\": \"0.55.5\",\n"
            + "\t\t\"benchmark\": \"0.117436617 s\",\n"
            + "\t\t\"totalResults\": 31,\n"
            + "\t\t\"serialQuery\": \"tokens:s:das\",\n"
            + "\t\t\"itemsPerPage\": 25\n"
            + "\t},\n"
            + "\t\"query\": {\n"
            + "\t\t\"@type\": \"koral:token\",\n"
            + "\t\t\"wrap\": {\n"
            + "\t\t\t\"@type\": \"koral:term\",\n"
            + "\t\t\t\"key\": \"das\",\n"
            + "\t\t\t\"layer\": \"orth\",\n"
            + "\t\t\t\"match\": \"match:eq\",\n"
            + "\t\t\t\"foundry\": \"opennlp\",\n"
            + "\t\t\t\"rewrites\": [{\n"
            + "\t\t\t\t\"@type\": \"koral:rewrite\",\n"
            + "\t\t\t\t\"src\": \"Kustvakt\",\n"
            + "\t\t\t\t\"operation\": \"operation:injection\",\n"
            + "\t\t\t\t\"scope\": \"foundry\"\n"
            + "\t\t\t}]\n"
            + "\t\t},\n"
            + "\t\t\"idn\": \"das_0\",\n"
            + "\t\t\"rewrites\": [{\n"
            + "\t\t\t\"@type\": \"koral:rewrite\",\n"
            + "\t\t\t\"src\": \"Kustvakt\",\n"
            + "\t\t\t\"operation\": \"operation:injection\",\n"
            + "\t\t\t\"scope\": \"idn\"\n"
            + "\t\t}]\n"
            + "\t},\n"
            + "\t\"collection\": {\n"
            + "\t\t\"@type\": \"koral:docGroup\",\n"
            + "\t\t\"operation\": \"operation:or\",\n"
            + "\t\t\"operands\": [{\n"
            + "\t\t\t\"@type\": \"koral:doc\",\n"
            + "\t\t\t\"key\": \"corpusSigle\",\n"
            + "\t\t\t\"value\": \"GOE\",\n"
            + "\t\t\t\"match\": \"match:eq\"\n"
            + "\t\t}, {\n"
            + "\t\t\t\"@type\": \"koral:doc\",\n"
            + "\t\t\t\"key\": \"corpusSigle\",\n"
            + "\t\t\t\"value\": \"WPD\",\n"
            + "\t\t\t\"match\": \"match:eq\"\n"
            + "\t\t}],\n"
            + "\t\t\"rewrites\": [{\n"
            + "\t\t\t\"@type\": \"koral:rewrite\",\n"
            + "\t\t\t\"src\": \"Kustvakt\",\n"
            + "\t\t\t\"operation\": \"operation:insertion\",\n"
            + "\t\t\t\"scope\": \"corpusSigle\"\n"
            + "\t\t}]\n"
            + "\t},\n"
            + "\t\"matches\": [{\n"
            + "\t\t\"field\": \"tokens\",\n"
            + "\t\t\"textClass\": \"wissenschaft populaerwissenschaft\",\n"
            + "\t\t\"pubPlace\": \"URL:http://de.wikipedia.org\",\n"
            + "\t\t\"textSigle\": \"WPD_AAA.00004\",\n"
            + "\t\t\"docSigle\": \"WPD_AAA\",\n"
            + "\t\t\"corpusSigle\": \"WPD\",\n"
            + "\t\t\"title\": \"A (Logik)\",\n"
            + "\t\t\"author\": \"Zenogantner; ElRaki; 1\",\n"
            + "\t\t\"layerInfos\": \"base/s=spans cnx/c=spans cnx/l=tokens cnx/m=tokens cnx/p=tokens cnx/s=spans cnx/syn=tokens corenlp/s=spans mate/l=tokens mate/m=tokens mate/p=tokens opennlp/p=tokens opennlp/s=spans tt/l=tokens tt/p=tokens tt/s=spans xip/c=spans xip/l=tokens xip/p=tokens xip/s=spans\",\n"
            + "\t\t\"startMore\": true,\n"
            + "\t\t\"endMore\": true,\n"
            + "\t\t\"snippet\": \"<span class=\\\"context-left\\\"><span class=\\\"more\\\"></span>z.B. mit dem Wort Barbara&quot; bezeichnet, </span><mark>das</mark><span class=\\\"context-right\\\"> dreimal den Buchstaben a enthält, aber<span class=\\\"more\\\"></span></span>\",\n"
            + "\t\t\"matchID\": \"match-WPD_AAA.00004-p195-196\",\n"
            + "\t\t\"UID\": 0,\n"
            + "\t\t\"pubDate\": \"2005-03-28\"\n"
            + "\t}, {\n"
            + "\t\t\"field\": \"tokens\",\n"
            + "\t\t\"textClass\": \"kultur musik freizeit-unterhaltung reisen\",\n"
            + "\t\t\"pubPlace\": \"URL:http://de.wikipedia.org\",\n"
            + "\t\t\"textSigle\": \"WPD_AAA.02439\",\n"
            + "\t\t\"docSigle\": \"WPD_AAA\",\n"
            + "\t\t\"corpusSigle\": \"WPD\",\n"
            + "\t\t\"title\": \"Aegukka\",\n"
            + "\t\t\"author\": \"ThorstenS; 2\",\n"
            + "\t\t\"layerInfos\": \"base/s=spans cnx/c=spans cnx/l=tokens cnx/m=tokens cnx/p=tokens cnx/s=spans cnx/syn=tokens corenlp/s=spans mate/l=tokens mate/m=tokens mate/p=tokens opennlp/p=tokens opennlp/s=spans tt/l=tokens tt/p=tokens tt/s=spans xip/c=spans xip/l=tokens xip/p=tokens xip/s=spans\",\n"
            + "\t\t\"startMore\": true,\n"
            + "\t\t\"endMore\": true,\n"
            + "\t\t\"snippet\": \"<span class=\\\"context-left\\\"><span class=\\\"more\\\"></span>wörtlich &quot;Das Lied der Liebe für </span><mark>das</mark><span class=\\\"context-right\\\"> Land&quot;, oder &quot;Das patriotische Lied&quot;. Es<span class=\\\"more\\\"></span></span>\",\n"
            + "\t\t\"matchID\": \"match-WPD_AAA.02439-p22-23\",\n"
            + "\t\t\"UID\": 0,\n"
            + "\t\t\"pubDate\": \"2005-03-28\"\n"
            + "\t}, {\n"
            + "\t\t\"field\": \"tokens\",\n"
            + "\t\t\"textClass\": \"kultur musik freizeit-unterhaltung reisen\",\n"
            + "\t\t\"pubPlace\": \"URL:http://de.wikipedia.org\",\n"
            + "\t\t\"textSigle\": \"WPD_AAA.02439\",\n"
            + "\t\t\"docSigle\": \"WPD_AAA\",\n"
            + "\t\t\"corpusSigle\": \"WPD\",\n"
            + "\t\t\"title\": \"Aegukka\",\n"
            + "\t\t\"author\": \"ThorstenS; 2\",\n"
            + "\t\t\"layerInfos\": \"base/s=spans cnx/c=spans cnx/l=tokens cnx/m=tokens cnx/p=tokens cnx/s=spans cnx/syn=tokens corenlp/s=spans mate/l=tokens mate/m=tokens mate/p=tokens opennlp/p=tokens opennlp/s=spans tt/l=tokens tt/p=tokens tt/s=spans xip/c=spans xip/l=tokens xip/p=tokens xip/s=spans\",\n"
            + "\t\t\"startMore\": true,\n"
            + "\t\t\"endMore\": true,\n"
            + "\t\t\"snippet\": \"<span class=\\\"context-left\\\"><span class=\\\"more\\\"></span>Besatzungszeit von 1910 bis 1945 wurde </span><mark>das</mark><span class=\\\"context-right\\\"> Lied verboten. Im Ausland lebende Koreaner<span class=\\\"more\\\"></span></span>\",\n"
            + "\t\t\"matchID\": \"match-WPD_AAA.02439-p74-75\",\n"
            + "\t\t\"UID\": 0,\n"
            + "\t\t\"pubDate\": \"2005-03-28\"\n"
            + "\t}, {\n"
            + "\t\t\"field\": \"tokens\",\n"
            + "\t\t\"textClass\": \"kultur musik freizeit-unterhaltung reisen\",\n"
            + "\t\t\"pubPlace\": \"URL:http://de.wikipedia.org\",\n"
            + "\t\t\"textSigle\": \"WPD_AAA.02439\",\n"
            + "\t\t\"docSigle\": \"WPD_AAA\",\n"
            + "\t\t\"corpusSigle\": \"WPD\",\n"
            + "\t\t\"title\": \"Aegukka\",\n"
            + "\t\t\"author\": \"ThorstenS; 2\",\n"
            + "\t\t\"layerInfos\": \"base/s=spans cnx/c=spans cnx/l=tokens cnx/m=tokens cnx/p=tokens cnx/s=spans cnx/syn=tokens corenlp/s=spans mate/l=tokens mate/m=tokens mate/p=tokens opennlp/p=tokens opennlp/s=spans tt/l=tokens tt/p=tokens tt/s=spans xip/c=spans xip/l=tokens xip/p=tokens xip/s=spans\",\n"
            + "\t\t\"startMore\": true,\n"
            + "\t\t\"endMore\": true,\n"
            + "\t\t\"snippet\": \"<span class=\\\"context-left\\\"><span class=\\\"more\\\"></span>3. Deutsche Übersetzung 1. Strophe Bis </span><mark>das</mark><span class=\\\"context-right\\\"> Meer des Ostens ausdörrt und der<span class=\\\"more\\\"></span></span>\",\n"
            + "\t\t\"matchID\": \"match-WPD_AAA.02439-p298-299\",\n"
            + "\t\t\"UID\": 0,\n"
            + "\t\t\"pubDate\": \"2005-03-28\"\n"
            + "\t}, {\n"
            + "\t\t\"field\": \"tokens\",\n"
            + "\t\t\"textClass\": \"freizeit-unterhaltung reisen wissenschaft populaerwissenschaft\",\n"
            + "\t\t\"pubPlace\": \"URL:http://de.wikipedia.org\",\n"
            + "\t\t\"textSigle\": \"WPD_AAA.00001\",\n"
            + "\t\t\"docSigle\": \"WPD_AAA\",\n"
            + "\t\t\"corpusSigle\": \"WPD\",\n"
            + "\t\t\"title\": \"A\",\n"
            + "\t\t\"author\": \"Ruru; Jens.Ol; Aglarech; u.a.\",\n"
            + "\t\t\"layerInfos\": \"base/s=spans cnx/c=spans cnx/l=tokens cnx/m=tokens cnx/p=tokens cnx/s=spans cnx/syn=tokens corenlp/s=spans mate/l=tokens mate/m=tokens mate/p=tokens opennlp/p=tokens opennlp/s=spans tt/l=tokens tt/p=tokens tt/s=spans xip/c=spans xip/l=tokens xip/p=tokens xip/s=spans\",\n"
            + "\t\t\"startMore\": true,\n"
            + "\t\t\"endMore\": true,\n"
            + "\t\t\"snippet\": \"<span class=\\\"context-left\\\"><span class=\\\"more\\\"></span>Ausnahme von Fremdwörtern und Namen ist </span><mark>das</mark><span class=\\\"context-right\\\"> A der einzige Buchstabe im Deutschen<span class=\\\"more\\\"></span></span>\",\n"
            + "\t\t\"matchID\": \"match-WPD_AAA.00001-p41-42\",\n"
            + "\t\t\"UID\": 0,\n"
            + "\t\t\"pubDate\": \"2005-03-28\"\n"
            + "\t}, {\n"
            + "\t\t\"field\": \"tokens\",\n"
            + "\t\t\"textClass\": \"freizeit-unterhaltung reisen wissenschaft populaerwissenschaft\",\n"
            + "\t\t\"pubPlace\": \"URL:http://de.wikipedia.org\",\n"
            + "\t\t\"textSigle\": \"WPD_AAA.00001\",\n"
            + "\t\t\"docSigle\": \"WPD_AAA\",\n"
            + "\t\t\"corpusSigle\": \"WPD\",\n"
            + "\t\t\"title\": \"A\",\n"
            + "\t\t\"author\": \"Ruru; Jens.Ol; Aglarech; u.a.\",\n"
            + "\t\t\"layerInfos\": \"base/s=spans cnx/c=spans cnx/l=tokens cnx/m=tokens cnx/p=tokens cnx/s=spans cnx/syn=tokens corenlp/s=spans mate/l=tokens mate/m=tokens mate/p=tokens opennlp/p=tokens opennlp/s=spans tt/l=tokens tt/p=tokens tt/s=spans xip/c=spans xip/l=tokens xip/p=tokens xip/s=spans\",\n"
            + "\t\t\"startMore\": true,\n"
            + "\t\t\"endMore\": true,\n"
            + "\t\t\"snippet\": \"<span class=\\\"context-left\\\"><span class=\\\"more\\\"></span>flache Stellung niedergedrückt wird. Stellt man </span><mark>das</mark><span class=\\\"context-right\\\"> Verhältnis der drei Hauptvokale a, i<span class=\\\"more\\\"></span></span>\",\n"
            + "\t\t\"matchID\": \"match-WPD_AAA.00001-p107-108\",\n"
            + "\t\t\"UID\": 0,\n"
            + "\t\t\"pubDate\": \"2005-03-28\"\n"
            + "\t}, {\n"
            + "\t\t\"field\": \"tokens\",\n"
            + "\t\t\"textClass\": \"freizeit-unterhaltung reisen wissenschaft populaerwissenschaft\",\n"
            + "\t\t\"pubPlace\": \"URL:http://de.wikipedia.org\",\n"
            + "\t\t\"textSigle\": \"WPD_AAA.00001\",\n"
            + "\t\t\"docSigle\": \"WPD_AAA\",\n"
            + "\t\t\"corpusSigle\": \"WPD\",\n"
            + "\t\t\"title\": \"A\",\n"
            + "\t\t\"author\": \"Ruru; Jens.Ol; Aglarech; u.a.\",\n"
            + "\t\t\"layerInfos\": \"base/s=spans cnx/c=spans cnx/l=tokens cnx/m=tokens cnx/p=tokens cnx/s=spans cnx/syn=tokens corenlp/s=spans mate/l=tokens mate/m=tokens mate/p=tokens opennlp/p=tokens opennlp/s=spans tt/l=tokens tt/p=tokens tt/s=spans xip/c=spans xip/l=tokens xip/p=tokens xip/s=spans\",\n"
            + "\t\t\"startMore\": true,\n"
            + "\t\t\"endMore\": true,\n"
            + "\t\t\"snippet\": \"<span class=\\\"context-left\\\"><span class=\\\"more\\\"></span>kommt i als der hellste an </span><mark>das</mark><span class=\\\"context-right\\\"> obere, u als der dumpfeste an<span class=\\\"more\\\"></span></span>\",\n"
            + "\t\t\"matchID\": \"match-WPD_AAA.00001-p127-128\",\n"
            + "\t\t\"UID\": 0,\n"
            + "\t\t\"pubDate\": \"2005-03-28\"\n"
            + "\t}, {\n"
            + "\t\t\"field\": \"tokens\",\n"
            + "\t\t\"textClass\": \"freizeit-unterhaltung reisen wissenschaft populaerwissenschaft\",\n"
            + "\t\t\"pubPlace\": \"URL:http://de.wikipedia.org\",\n"
            + "\t\t\"textSigle\": \"WPD_AAA.00001\",\n"
            + "\t\t\"docSigle\": \"WPD_AAA\",\n"
            + "\t\t\"corpusSigle\": \"WPD\",\n"
            + "\t\t\"title\": \"A\",\n"
            + "\t\t\"author\": \"Ruru; Jens.Ol; Aglarech; u.a.\",\n"
            + "\t\t\"layerInfos\": \"base/s=spans cnx/c=spans cnx/l=tokens cnx/m=tokens cnx/p=tokens cnx/s=spans cnx/syn=tokens corenlp/s=spans mate/l=tokens mate/m=tokens mate/p=tokens opennlp/p=tokens opennlp/s=spans tt/l=tokens tt/p=tokens tt/s=spans xip/c=spans xip/l=tokens xip/p=tokens xip/s=spans\",\n"
            + "\t\t\"startMore\": true,\n"
            + "\t\t\"endMore\": true,\n"
            + "\t\t\"snippet\": \"<span class=\\\"context-left\\\"><span class=\\\"more\\\"></span>obere, u als der dumpfeste an </span><mark>das</mark><span class=\\\"context-right\\\"> untere Ende, a als der mittlere<span class=\\\"more\\\"></span></span>\",\n"
            + "\t\t\"matchID\": \"match-WPD_AAA.00001-p134-135\",\n"
            + "\t\t\"UID\": 0,\n"
            + "\t\t\"pubDate\": \"2005-03-28\"\n"
            + "\t}, {\n"
            + "\t\t\"field\": \"tokens\",\n"
            + "\t\t\"textClass\": \"freizeit-unterhaltung reisen wissenschaft populaerwissenschaft\",\n"
            + "\t\t\"pubPlace\": \"URL:http://de.wikipedia.org\",\n"
            + "\t\t\"textSigle\": \"WPD_AAA.00001\",\n"
            + "\t\t\"docSigle\": \"WPD_AAA\",\n"
            + "\t\t\"corpusSigle\": \"WPD\",\n"
            + "\t\t\"title\": \"A\",\n"
            + "\t\t\"author\": \"Ruru; Jens.Ol; Aglarech; u.a.\",\n"
            + "\t\t\"layerInfos\": \"base/s=spans cnx/c=spans cnx/l=tokens cnx/m=tokens cnx/p=tokens cnx/s=spans cnx/syn=tokens corenlp/s=spans mate/l=tokens mate/m=tokens mate/p=tokens opennlp/p=tokens opennlp/s=spans tt/l=tokens tt/p=tokens tt/s=spans xip/c=spans xip/l=tokens xip/p=tokens xip/s=spans\",\n"
            + "\t\t\"startMore\": true,\n"
            + "\t\t\"endMore\": true,\n"
            + "\t\t\"snippet\": \"<span class=\\\"context-left\\\"><span class=\\\"more\\\"></span>im 9. Jahrhundert v. Chr. war </span><mark>das</mark><span class=\\\"context-right\\\"> Schriftzeichen bereits stark stilisiert, die Hörner<span class=\\\"more\\\"></span></span>\",\n"
            + "\t\t\"matchID\": \"match-WPD_AAA.00001-p271-272\",\n"
            + "\t\t\"UID\": 0,\n"
            + "\t\t\"pubDate\": \"2005-03-28\"\n"
            + "\t}, {\n"
            + "\t\t\"field\": \"tokens\",\n"
            + "\t\t\"textClass\": \"freizeit-unterhaltung reisen wissenschaft populaerwissenschaft\",\n"
            + "\t\t\"pubPlace\": \"URL:http://de.wikipedia.org\",\n"
            + "\t\t\"textSigle\": \"WPD_AAA.00001\",\n"
            + "\t\t\"docSigle\": \"WPD_AAA\",\n"
            + "\t\t\"corpusSigle\": \"WPD\",\n"
            + "\t\t\"title\": \"A\",\n"
            + "\t\t\"author\": \"Ruru; Jens.Ol; Aglarech; u.a.\",\n"
            + "\t\t\"layerInfos\": \"base/s=spans cnx/c=spans cnx/l=tokens cnx/m=tokens cnx/p=tokens cnx/s=spans cnx/syn=tokens corenlp/s=spans mate/l=tokens mate/m=tokens mate/p=tokens opennlp/p=tokens opennlp/s=spans tt/l=tokens tt/p=tokens tt/s=spans xip/c=spans xip/l=tokens xip/p=tokens xip/s=spans\",\n"
            + "\t\t\"startMore\": true,\n"
            + "\t\t\"endMore\": true,\n"
            + "\t\t\"snippet\": \"<span class=\\\"context-left\\\"><span class=\\\"more\\\"></span>im Alphabet inne. Als die Griechen </span><mark>das</mark><span class=\\\"context-right\\\"> Phönizische Alphabet übernamen, drehten sie das<span class=\\\"more\\\"></span></span>\",\n"
            + "\t\t\"matchID\": \"match-WPD_AAA.00001-p313-314\",\n"
            + "\t\t\"UID\": 0,\n"
            + "\t\t\"pubDate\": \"2005-03-28\"\n"
            + "\t}, {\n"
            + "\t\t\"field\": \"tokens\",\n"
            + "\t\t\"textClass\": \"freizeit-unterhaltung reisen wissenschaft populaerwissenschaft\",\n"
            + "\t\t\"pubPlace\": \"URL:http://de.wikipedia.org\",\n"
            + "\t\t\"textSigle\": \"WPD_AAA.00001\",\n"
            + "\t\t\"docSigle\": \"WPD_AAA\",\n"
            + "\t\t\"corpusSigle\": \"WPD\",\n"
            + "\t\t\"title\": \"A\",\n"
            + "\t\t\"author\": \"Ruru; Jens.Ol; Aglarech; u.a.\",\n"
            + "\t\t\"layerInfos\": \"base/s=spans cnx/c=spans cnx/l=tokens cnx/m=tokens cnx/p=tokens cnx/s=spans cnx/syn=tokens corenlp/s=spans mate/l=tokens mate/m=tokens mate/p=tokens opennlp/p=tokens opennlp/s=spans tt/l=tokens tt/p=tokens tt/s=spans xip/c=spans xip/l=tokens xip/p=tokens xip/s=spans\",\n"
            + "\t\t\"startMore\": true,\n"
            + "\t\t\"endMore\": true,\n"
            + "\t\t\"snippet\": \"<span class=\\\"context-left\\\"><span class=\\\"more\\\"></span>das Phönizische Alphabet übernamen, drehten sie </span><mark>das</mark><span class=\\\"context-right\\\"> Zeichen um 90 Grad und machten<span class=\\\"more\\\"></span></span>\",\n"
            + "\t\t\"matchID\": \"match-WPD_AAA.00001-p319-320\",\n"
            + "\t\t\"UID\": 0,\n"
            + "\t\t\"pubDate\": \"2005-03-28\"\n"
            + "\t}, {\n"
            + "\t\t\"field\": \"tokens\",\n"
            + "\t\t\"textClass\": \"freizeit-unterhaltung reisen wissenschaft populaerwissenschaft\",\n"
            + "\t\t\"pubPlace\": \"URL:http://de.wikipedia.org\",\n"
            + "\t\t\"textSigle\": \"WPD_AAA.00001\",\n"
            + "\t\t\"docSigle\": \"WPD_AAA\",\n"
            + "\t\t\"corpusSigle\": \"WPD\",\n"
            + "\t\t\"title\": \"A\",\n"
            + "\t\t\"author\": \"Ruru; Jens.Ol; Aglarech; u.a.\",\n"
            + "\t\t\"layerInfos\": \"base/s=spans cnx/c=spans cnx/l=tokens cnx/m=tokens cnx/p=tokens cnx/s=spans cnx/syn=tokens corenlp/s=spans mate/l=tokens mate/m=tokens mate/p=tokens opennlp/p=tokens opennlp/s=spans tt/l=tokens tt/p=tokens tt/s=spans xip/c=spans xip/l=tokens xip/p=tokens xip/s=spans\",\n"
            + "\t\t\"startMore\": true,\n"
            + "\t\t\"endMore\": true,\n"
            + "\t\t\"snippet\": \"<span class=\\\"context-left\\\"><span class=\\\"more\\\"></span>um 90 Grad und machten daraus </span><mark>das</mark><span class=\\\"context-right\\\"> Alpha. Da das Griechische reich an<span class=\\\"more\\\"></span></span>\",\n"
            + "\t\t\"matchID\": \"match-WPD_AAA.00001-p327-328\",\n"
            + "\t\t\"UID\": 0,\n"
            + "\t\t\"pubDate\": \"2005-03-28\"\n"
            + "\t}, {\n"
            + "\t\t\"field\": \"tokens\",\n"
            + "\t\t\"textClass\": \"freizeit-unterhaltung reisen wissenschaft populaerwissenschaft\",\n"
            + "\t\t\"pubPlace\": \"URL:http://de.wikipedia.org\",\n"
            + "\t\t\"textSigle\": \"WPD_AAA.00001\",\n"
            + "\t\t\"docSigle\": \"WPD_AAA\",\n"
            + "\t\t\"corpusSigle\": \"WPD\",\n"
            + "\t\t\"title\": \"A\",\n"
            + "\t\t\"author\": \"Ruru; Jens.Ol; Aglarech; u.a.\",\n"
            + "\t\t\"layerInfos\": \"base/s=spans cnx/c=spans cnx/l=tokens cnx/m=tokens cnx/p=tokens cnx/s=spans cnx/syn=tokens corenlp/s=spans mate/l=tokens mate/m=tokens mate/p=tokens opennlp/p=tokens opennlp/s=spans tt/l=tokens tt/p=tokens tt/s=spans xip/c=spans xip/l=tokens xip/p=tokens xip/s=spans\",\n"
            + "\t\t\"startMore\": true,\n"
            + "\t\t\"endMore\": true,\n"
            + "\t\t\"snippet\": \"<span class=\\\"context-left\\\"><span class=\\\"more\\\"></span>und machten daraus das Alpha. Da </span><mark>das</mark><span class=\\\"context-right\\\"> Griechische reich an Vokalen war, verwendeten<span class=\\\"more\\\"></span></span>\",\n"
            + "\t\t\"matchID\": \"match-WPD_AAA.00001-p330-331\",\n"
            + "\t\t\"UID\": 0,\n"
            + "\t\t\"pubDate\": \"2005-03-28\"\n"
            + "\t}, {\n"
            + "\t\t\"field\": \"tokens\",\n"
            + "\t\t\"textClass\": \"freizeit-unterhaltung reisen wissenschaft populaerwissenschaft\",\n"
            + "\t\t\"pubPlace\": \"URL:http://de.wikipedia.org\",\n"
            + "\t\t\"textSigle\": \"WPD_AAA.00001\",\n"
            + "\t\t\"docSigle\": \"WPD_AAA\",\n"
            + "\t\t\"corpusSigle\": \"WPD\",\n"
            + "\t\t\"title\": \"A\",\n"
            + "\t\t\"author\": \"Ruru; Jens.Ol; Aglarech; u.a.\",\n"
            + "\t\t\"layerInfos\": \"base/s=spans cnx/c=spans cnx/l=tokens cnx/m=tokens cnx/p=tokens cnx/s=spans cnx/syn=tokens corenlp/s=spans mate/l=tokens mate/m=tokens mate/p=tokens opennlp/p=tokens opennlp/s=spans tt/l=tokens tt/p=tokens tt/s=spans xip/c=spans xip/l=tokens xip/p=tokens xip/s=spans\",\n"
            + "\t\t\"startMore\": true,\n"
            + "\t\t\"endMore\": true,\n"
            + "\t\t\"snippet\": \"<span class=\\\"context-left\\\"><span class=\\\"more\\\"></span>reich an Vokalen war, verwendeten sie </span><mark>das</mark><span class=\\\"context-right\\\"> Zeichen für den Lautwert a. Die<span class=\\\"more\\\"></span></span>\",\n"
            + "\t\t\"matchID\": \"match-WPD_AAA.00001-p338-339\",\n"
            + "\t\t\"UID\": 0,\n"
            + "\t\t\"pubDate\": \"2005-03-28\"\n"
            + "\t}, {\n"
            + "\t\t\"field\": \"tokens\",\n"
            + "\t\t\"textClass\": \"freizeit-unterhaltung reisen wissenschaft populaerwissenschaft\",\n"
            + "\t\t\"pubPlace\": \"URL:http://de.wikipedia.org\",\n"
            + "\t\t\"textSigle\": \"WPD_AAA.00001\",\n"
            + "\t\t\"docSigle\": \"WPD_AAA\",\n"
            + "\t\t\"corpusSigle\": \"WPD\",\n"
            + "\t\t\"title\": \"A\",\n"
            + "\t\t\"author\": \"Ruru; Jens.Ol; Aglarech; u.a.\",\n"
            + "\t\t\"layerInfos\": \"base/s=spans cnx/c=spans cnx/l=tokens cnx/m=tokens cnx/p=tokens cnx/s=spans cnx/syn=tokens corenlp/s=spans mate/l=tokens mate/m=tokens mate/p=tokens opennlp/p=tokens opennlp/s=spans tt/l=tokens tt/p=tokens tt/s=spans xip/c=spans xip/l=tokens xip/p=tokens xip/s=spans\",\n"
            + "\t\t\"startMore\": true,\n"
            + "\t\t\"endMore\": true,\n"
            + "\t\t\"snippet\": \"<span class=\\\"context-left\\\"><span class=\\\"more\\\"></span>den Lautwert a. Die Etrusker übernahmen </span><mark>das</mark><span class=\\\"context-right\\\"> frühgriechische Alpha und ließen es größtenteils<span class=\\\"more\\\"></span></span>\",\n"
            + "\t\t\"matchID\": \"match-WPD_AAA.00001-p347-348\",\n"
            + "\t\t\"UID\": 0,\n"
            + "\t\t\"pubDate\": \"2005-03-28\"\n"
            + "\t}, {\n"
            + "\t\t\"field\": \"tokens\",\n"
            + "\t\t\"textClass\": \"freizeit-unterhaltung reisen wissenschaft populaerwissenschaft\",\n"
            + "\t\t\"pubPlace\": \"URL:http://de.wikipedia.org\",\n"
            + "\t\t\"textSigle\": \"WPD_AAA.00001\",\n"
            + "\t\t\"docSigle\": \"WPD_AAA\",\n"
            + "\t\t\"corpusSigle\": \"WPD\",\n"
            + "\t\t\"title\": \"A\",\n"
            + "\t\t\"author\": \"Ruru; Jens.Ol; Aglarech; u.a.\",\n"
            + "\t\t\"layerInfos\": \"base/s=spans cnx/c=spans cnx/l=tokens cnx/m=tokens cnx/p=tokens cnx/s=spans cnx/syn=tokens corenlp/s=spans mate/l=tokens mate/m=tokens mate/p=tokens opennlp/p=tokens opennlp/s=spans tt/l=tokens tt/p=tokens tt/s=spans xip/c=spans xip/l=tokens xip/p=tokens xip/s=spans\",\n"
            + "\t\t\"startMore\": true,\n"
            + "\t\t\"endMore\": true,\n"
            + "\t\t\"snippet\": \"<span class=\\\"context-left\\\"><span class=\\\"more\\\"></span>von rechts nach links) versahen sie </span><mark>das</mark><span class=\\\"context-right\\\"> Zeichen mit einem Abschwung nach links<span class=\\\"more\\\"></span></span>\",\n"
            + "\t\t\"matchID\": \"match-WPD_AAA.00001-p365-366\",\n"
            + "\t\t\"UID\": 0,\n"
            + "\t\t\"pubDate\": \"2005-03-28\"\n"
            + "\t}, {\n"
            + "\t\t\"field\": \"tokens\",\n"
            + "\t\t\"textClass\": \"freizeit-unterhaltung reisen wissenschaft populaerwissenschaft\",\n"
            + "\t\t\"pubPlace\": \"URL:http://de.wikipedia.org\",\n"
            + "\t\t\"textSigle\": \"WPD_AAA.00001\",\n"
            + "\t\t\"docSigle\": \"WPD_AAA\",\n"
            + "\t\t\"corpusSigle\": \"WPD\",\n"
            + "\t\t\"title\": \"A\",\n"
            + "\t\t\"author\": \"Ruru; Jens.Ol; Aglarech; u.a.\",\n"
            + "\t\t\"layerInfos\": \"base/s=spans cnx/c=spans cnx/l=tokens cnx/m=tokens cnx/p=tokens cnx/s=spans cnx/syn=tokens corenlp/s=spans mate/l=tokens mate/m=tokens mate/p=tokens opennlp/p=tokens opennlp/s=spans tt/l=tokens tt/p=tokens tt/s=spans xip/c=spans xip/l=tokens xip/p=tokens xip/s=spans\",\n"
            + "\t\t\"startMore\": true,\n"
            + "\t\t\"endMore\": true,\n"
            + "\t\t\"snippet\": \"<span class=\\\"context-left\\\"><span class=\\\"more\\\"></span>Abschwung nach links. Als die Römer </span><mark>das</mark><span class=\\\"context-right\\\"> lateinische Alphabet schufen, verwendeten sie das<span class=\\\"more\\\"></span></span>\",\n"
            + "\t\t\"matchID\": \"match-WPD_AAA.00001-p375-376\",\n"
            + "\t\t\"UID\": 0,\n"
            + "\t\t\"pubDate\": \"2005-03-28\"\n"
            + "\t}, {\n"
            + "\t\t\"field\": \"tokens\",\n"
            + "\t\t\"textClass\": \"freizeit-unterhaltung reisen wissenschaft populaerwissenschaft\",\n"
            + "\t\t\"pubPlace\": \"URL:http://de.wikipedia.org\",\n"
            + "\t\t\"textSigle\": \"WPD_AAA.00001\",\n"
            + "\t\t\"docSigle\": \"WPD_AAA\",\n"
            + "\t\t\"corpusSigle\": \"WPD\",\n"
            + "\t\t\"title\": \"A\",\n"
            + "\t\t\"author\": \"Ruru; Jens.Ol; Aglarech; u.a.\",\n"
            + "\t\t\"layerInfos\": \"base/s=spans cnx/c=spans cnx/l=tokens cnx/m=tokens cnx/p=tokens cnx/s=spans cnx/syn=tokens corenlp/s=spans mate/l=tokens mate/m=tokens mate/p=tokens opennlp/p=tokens opennlp/s=spans tt/l=tokens tt/p=tokens tt/s=spans xip/c=spans xip/l=tokens xip/p=tokens xip/s=spans\",\n"
            + "\t\t\"startMore\": true,\n"
            + "\t\t\"endMore\": true,\n"
            + "\t\t\"snippet\": \"<span class=\\\"context-left\\\"><span class=\\\"more\\\"></span>das lateinische Alphabet schufen, verwendeten sie </span><mark>das</mark><span class=\\\"context-right\\\"> A aus dem etruskischen Alphabet, der<span class=\\\"more\\\"></span></span>\",\n"
            + "\t\t\"matchID\": \"match-WPD_AAA.00001-p381-382\",\n"
            + "\t\t\"UID\": 0,\n"
            + "\t\t\"pubDate\": \"2005-03-28\"\n"
            + "\t}, {\n"
            + "\t\t\"field\": \"tokens\",\n"
            + "\t\t\"textClass\": \"freizeit-unterhaltung reisen wissenschaft populaerwissenschaft\",\n"
            + "\t\t\"pubPlace\": \"URL:http://de.wikipedia.org\",\n"
            + "\t\t\"textSigle\": \"WPD_AAA.00001\",\n"
            + "\t\t\"docSigle\": \"WPD_AAA\",\n"
            + "\t\t\"corpusSigle\": \"WPD\",\n"
            + "\t\t\"title\": \"A\",\n"
            + "\t\t\"author\": \"Ruru; Jens.Ol; Aglarech; u.a.\",\n"
            + "\t\t\"layerInfos\": \"base/s=spans cnx/c=spans cnx/l=tokens cnx/m=tokens cnx/p=tokens cnx/s=spans cnx/syn=tokens corenlp/s=spans mate/l=tokens mate/m=tokens mate/p=tokens opennlp/p=tokens opennlp/s=spans tt/l=tokens tt/p=tokens tt/s=spans xip/c=spans xip/l=tokens xip/p=tokens xip/s=spans\",\n"
            + "\t\t\"startMore\": true,\n"
            + "\t\t\"endMore\": true,\n"
            + "\t\t\"snippet\": \"<span class=\\\"context-left\\\"><span class=\\\"more\\\"></span>in der Biologie steht A für </span><mark>das</mark><span class=\\\"context-right\\\"> Nukleosid Adenosin steht A die Base<span class=\\\"more\\\"></span></span>\",\n"
            + "\t\t\"matchID\": \"match-WPD_AAA.00001-p404-405\",\n"
            + "\t\t\"UID\": 0,\n"
            + "\t\t\"pubDate\": \"2005-03-28\"\n"
            + "\t}, {\n"
            + "\t\t\"field\": \"tokens\",\n"
            + "\t\t\"textClass\": \"freizeit-unterhaltung reisen wissenschaft populaerwissenschaft\",\n"
            + "\t\t\"pubPlace\": \"URL:http://de.wikipedia.org\",\n"
            + "\t\t\"textSigle\": \"WPD_AAA.00001\",\n"
            + "\t\t\"docSigle\": \"WPD_AAA\",\n"
            + "\t\t\"corpusSigle\": \"WPD\",\n"
            + "\t\t\"title\": \"A\",\n"
            + "\t\t\"author\": \"Ruru; Jens.Ol; Aglarech; u.a.\",\n"
            + "\t\t\"layerInfos\": \"base/s=spans cnx/c=spans cnx/l=tokens cnx/m=tokens cnx/p=tokens cnx/s=spans cnx/syn=tokens corenlp/s=spans mate/l=tokens mate/m=tokens mate/p=tokens opennlp/p=tokens opennlp/s=spans tt/l=tokens tt/p=tokens tt/s=spans xip/c=spans xip/l=tokens xip/p=tokens xip/s=spans\",\n"
            + "\t\t\"startMore\": true,\n"
            + "\t\t\"endMore\": true,\n"
            + "\t\t\"snippet\": \"<span class=\\\"context-left\\\"><span class=\\\"more\\\"></span>Wert 10, siehe auch Hexadezimalsystem. steht </span><mark>das</mark><span class=\\\"context-right\\\"> Symbol ∀ (ein auf den Kopf gestelltes<span class=\\\"more\\\"></span></span>\",\n"
            + "\t\t\"matchID\": \"match-WPD_AAA.00001-p526-527\",\n"
            + "\t\t\"UID\": 0,\n"
            + "\t\t\"pubDate\": \"2005-03-28\"\n"
            + "\t}, {\n"
            + "\t\t\"field\": \"tokens\",\n"
            + "\t\t\"textClass\": \"freizeit-unterhaltung reisen wissenschaft populaerwissenschaft\",\n"
            + "\t\t\"pubPlace\": \"URL:http://de.wikipedia.org\",\n"
            + "\t\t\"textSigle\": \"WPD_AAA.00001\",\n"
            + "\t\t\"docSigle\": \"WPD_AAA\",\n"
            + "\t\t\"corpusSigle\": \"WPD\",\n"
            + "\t\t\"title\": \"A\",\n"
            + "\t\t\"author\": \"Ruru; Jens.Ol; Aglarech; u.a.\",\n"
            + "\t\t\"layerInfos\": \"base/s=spans cnx/c=spans cnx/l=tokens cnx/m=tokens cnx/p=tokens cnx/s=spans cnx/syn=tokens corenlp/s=spans mate/l=tokens mate/m=tokens mate/p=tokens opennlp/p=tokens opennlp/s=spans tt/l=tokens tt/p=tokens tt/s=spans xip/c=spans xip/l=tokens xip/p=tokens xip/s=spans\",\n"
            + "\t\t\"startMore\": true,\n"
            + "\t\t\"endMore\": true,\n"
            + "\t\t\"snippet\": \"<span class=\\\"context-left\\\"><span class=\\\"more\\\"></span>für die Vorsilbe Atto ist A </span><mark>das</mark><span class=\\\"context-right\\\"> Einheitensymbol der elektrischen Stromstärke Ampere in<span class=\\\"more\\\"></span></span>\",\n"
            + "\t\t\"matchID\": \"match-WPD_AAA.00001-p624-625\",\n"
            + "\t\t\"UID\": 0,\n"
            + "\t\t\"pubDate\": \"2005-03-28\"\n"
            + "\t}, {\n"
            + "\t\t\"field\": \"tokens\",\n"
            + "\t\t\"textClass\": \"freizeit-unterhaltung reisen wissenschaft populaerwissenschaft\",\n"
            + "\t\t\"pubPlace\": \"URL:http://de.wikipedia.org\",\n"
            + "\t\t\"textSigle\": \"WPD_AAA.00001\",\n"
            + "\t\t\"docSigle\": \"WPD_AAA\",\n"
            + "\t\t\"corpusSigle\": \"WPD\",\n"
            + "\t\t\"title\": \"A\",\n"
            + "\t\t\"author\": \"Ruru; Jens.Ol; Aglarech; u.a.\",\n"
            + "\t\t\"layerInfos\": \"base/s=spans cnx/c=spans cnx/l=tokens cnx/m=tokens cnx/p=tokens cnx/s=spans cnx/syn=tokens corenlp/s=spans mate/l=tokens mate/m=tokens mate/p=tokens opennlp/p=tokens opennlp/s=spans tt/l=tokens tt/p=tokens tt/s=spans xip/c=spans xip/l=tokens xip/p=tokens xip/s=spans\",\n"
            + "\t\t\"startMore\": true,\n"
            + "\t\t\"endMore\": true,\n"
            + "\t\t\"snippet\": \"<span class=\\\"context-left\\\"><span class=\\\"more\\\"></span>Anordnung (Rechtswesen), Agent (Börse), Aufzeichung (Rechtsw.), </span><mark>das</mark><span class=\\\"context-right\\\"> Flächenmaß Acre und Ausgabe A ist<span class=\\\"more\\\"></span></span>\",\n"
            + "\t\t\"matchID\": \"match-WPD_AAA.00001-p757-758\",\n"
            + "\t\t\"UID\": 0,\n"
            + "\t\t\"pubDate\": \"2005-03-28\"\n"
            + "\t}, {\n"
            + "\t\t\"field\": \"tokens\",\n"
            + "\t\t\"textClass\": \"freizeit-unterhaltung reisen wissenschaft populaerwissenschaft\",\n"
            + "\t\t\"pubPlace\": \"URL:http://de.wikipedia.org\",\n"
            + "\t\t\"textSigle\": \"WPD_AAA.00001\",\n"
            + "\t\t\"docSigle\": \"WPD_AAA\",\n"
            + "\t\t\"corpusSigle\": \"WPD\",\n"
            + "\t\t\"title\": \"A\",\n"
            + "\t\t\"author\": \"Ruru; Jens.Ol; Aglarech; u.a.\",\n"
            + "\t\t\"layerInfos\": \"base/s=spans cnx/c=spans cnx/l=tokens cnx/m=tokens cnx/p=tokens cnx/s=spans cnx/syn=tokens corenlp/s=spans mate/l=tokens mate/m=tokens mate/p=tokens opennlp/p=tokens opennlp/s=spans tt/l=tokens tt/p=tokens tt/s=spans xip/c=spans xip/l=tokens xip/p=tokens xip/s=spans\",\n"
            + "\t\t\"startMore\": true,\n"
            + "\t\t\"endMore\": true,\n"
            + "\t\t\"snippet\": \"<span class=\\\"context-left\\\"><span class=\\\"more\\\"></span>Band). in Redewendungen für den Anfang (</span><mark>das</mark><span class=\\\"context-right\\\"> A und O, von A bis<span class=\\\"more\\\"></span></span>\",\n"
            + "\t\t\"matchID\": \"match-WPD_AAA.00001-p777-778\",\n"
            + "\t\t\"UID\": 0,\n"
            + "\t\t\"pubDate\": \"2005-03-28\"\n"
            + "\t}, {\n"
            + "\t\t\"field\": \"tokens\",\n"
            + "\t\t\"textClass\": \"freizeit-unterhaltung reisen wissenschaft populaerwissenschaft\",\n"
            + "\t\t\"pubPlace\": \"URL:http://de.wikipedia.org\",\n"
            + "\t\t\"textSigle\": \"WPD_AAA.00001\",\n"
            + "\t\t\"docSigle\": \"WPD_AAA\",\n"
            + "\t\t\"corpusSigle\": \"WPD\",\n"
            + "\t\t\"title\": \"A\",\n"
            + "\t\t\"author\": \"Ruru; Jens.Ol; Aglarech; u.a.\",\n"
            + "\t\t\"layerInfos\": \"base/s=spans cnx/c=spans cnx/l=tokens cnx/m=tokens cnx/p=tokens cnx/s=spans cnx/syn=tokens corenlp/s=spans mate/l=tokens mate/m=tokens mate/p=tokens opennlp/p=tokens opennlp/s=spans tt/l=tokens tt/p=tokens tt/s=spans xip/c=spans xip/l=tokens xip/p=tokens xip/s=spans\",\n"
            + "\t\t\"startMore\": true,\n"
            + "\t\t\"endMore\": true,\n"
            + "\t\t\"snippet\": \"<span class=\\\"context-left\\\"><span class=\\\"more\\\"></span>Z). a ist die Abkürzung für </span><mark>das</mark><span class=\\\"context-right\\\"> Flächenmaß Ar in der Kaufmannssprache bedeutet<span class=\\\"more\\\"></span></span>\",\n"
            + "\t\t\"matchID\": \"match-WPD_AAA.00001-p790-791\",\n"
            + "\t\t\"UID\": 0,\n"
            + "\t\t\"pubDate\": \"2005-03-28\"\n"
            + "\t}, {\n"
            + "\t\t\"field\": \"tokens\",\n"
            + "\t\t\"textClass\": \"freizeit-unterhaltung reisen wissenschaft populaerwissenschaft\",\n"
            + "\t\t\"pubPlace\": \"URL:http://de.wikipedia.org\",\n"
            + "\t\t\"textSigle\": \"WPD_AAA.00001\",\n"
            + "\t\t\"docSigle\": \"WPD_AAA\",\n"
            + "\t\t\"corpusSigle\": \"WPD\",\n"
            + "\t\t\"title\": \"A\",\n"
            + "\t\t\"author\": \"Ruru; Jens.Ol; Aglarech; u.a.\",\n"
            + "\t\t\"layerInfos\": \"base/s=spans cnx/c=spans cnx/l=tokens cnx/m=tokens cnx/p=tokens cnx/s=spans cnx/syn=tokens corenlp/s=spans mate/l=tokens mate/m=tokens mate/p=tokens opennlp/p=tokens opennlp/s=spans tt/l=tokens tt/p=tokens tt/s=spans xip/c=spans xip/l=tokens xip/p=tokens xip/s=spans\",\n"
            + "\t\t\"startMore\": true,\n"
            + "\t\t\"endMore\": true,\n"
            + "\t\t\"snippet\": \"<span class=\\\"context-left\\\"><span class=\\\"more\\\"></span>ad zu) ‚[das Stück] zu...‘ für </span><mark>das</mark><span class=\\\"context-right\\\"> Französische à „nach“, z. B. in<span class=\\\"more\\\"></span></span>\",\n"
            + "\t\t\"matchID\": \"match-WPD_AAA.00001-p805-806\",\n"
            + "\t\t\"UID\": 0,\n" + "\t\t\"pubDate\": \"2005-03-28\"\n"
            + "\t}]\n" + "}";


}
