INSERT INTO "annotation_layer" VALUES(1,1,2,'OpenNLP Part-of-Speech');
INSERT INTO "annotation_layer" VALUES(2,55,56,'Mate Lemma');
INSERT INTO "annotation_layer" VALUES(3,55,57,'Mate Morphology');
INSERT INTO "annotation_layer" VALUES(4,55,2,'Mate Part-of-Speech');
INSERT INTO "annotation_layer" VALUES(5,88,89,'Malt Dependency');
INSERT INTO "annotation_layer" VALUES(6,123,56,'DRuKoLa Lemma');
INSERT INTO "annotation_layer" VALUES(7,123,57,'DRuKoLa Morphology');
INSERT INTO "annotation_layer" VALUES(8,123,2,'DRuKoLa Part-of-Speech');
INSERT INTO "annotation_layer" VALUES(9,211,212,'Connexor Constituency');
INSERT INTO "annotation_layer" VALUES(10,211,56,'Connexor Lemma');
INSERT INTO "annotation_layer" VALUES(11,211,57,'Connexor Morphology');
INSERT INTO "annotation_layer" VALUES(12,211,2,'Connexor Part-of-Speech');
INSERT INTO "annotation_layer" VALUES(13,211,213,'Connexor Syntax');
INSERT INTO "annotation_layer" VALUES(14,247,57,'MarMoT Morphology');
INSERT INTO "annotation_layer" VALUES(15,247,2,'MarMoT Part-of-Speech');
INSERT INTO "annotation_layer" VALUES(16,248,249,'Base Annotation Structure');
INSERT INTO "annotation_layer" VALUES(17,253,212,'Xerox Parser Constituency');
INSERT INTO "annotation_layer" VALUES(18,253,56,'Xerox Parser Lemma');
INSERT INTO "annotation_layer" VALUES(19,253,2,'Xerox Parser Part-of-Speech');
INSERT INTO "annotation_layer" VALUES(20,254,89,'LWC Dependency');
INSERT INTO "annotation_layer" VALUES(21,297,249,'DeReKo Structure');
INSERT INTO "annotation_layer" VALUES(22,298,56,'Schreibgebrauch Lemma');
INSERT INTO "annotation_layer" VALUES(23,298,299,'Schreibgebrauch Lemma Variants');
INSERT INTO "annotation_layer" VALUES(24,298,2,'Schreibgebrauch Part-of-Speech');
INSERT INTO "annotation_layer" VALUES(25,317,212,'CoreNLP Constituency');
INSERT INTO "annotation_layer" VALUES(26,317,318,'CoreNLP Named Entity');
INSERT INTO "annotation_layer" VALUES(27,317,319,'CoreNLP Named Entity');
INSERT INTO "annotation_layer" VALUES(28,317,320,'CoreNLP Named Entity');
INSERT INTO "annotation_layer" VALUES(29,317,2,'CoreNLP Part-of-Speech');
INSERT INTO "annotation_layer" VALUES(30,391,56,'TreeTagger Lemma');
INSERT INTO "annotation_layer" VALUES(31,391,2,'TreeTagger Part-of-Speech');
