INSERT INTO "annotation" VALUES(1,'opennlp','foundry',NULL,'OpenNLP',NULL);
INSERT INTO "annotation" VALUES(2,'p','layer',NULL,'Part-of-Speech',NULL);
INSERT INTO "annotation" VALUES(3,'ADJA','key','ADJA ','Attributive Adjective',NULL);
INSERT INTO "annotation" VALUES(4,'ADJD','key','ADJD ','Predicative Adjective',NULL);
INSERT INTO "annotation" VALUES(5,'ADV','key','ADV ','Adverb',NULL);
INSERT INTO "annotation" VALUES(6,'APPO','key','APPO ','Postposition',NULL);
INSERT INTO "annotation" VALUES(7,'APPR','key','APPR ','Preposition',NULL);
INSERT INTO "annotation" VALUES(8,'APPRART','key','APPRART ','Preposition with Determiner',NULL);
INSERT INTO "annotation" VALUES(9,'APZR','key','APZR ','Right Circumposition',NULL);
INSERT INTO "annotation" VALUES(10,'ART','key','ART ','Determiner',NULL);
INSERT INTO "annotation" VALUES(11,'CARD','key','CARD ','Cardinal Number',NULL);
INSERT INTO "annotation" VALUES(12,'FM','key','FM ','Foreign Material',NULL);
INSERT INTO "annotation" VALUES(13,'ITJ','key','ITJ ','Interjection',NULL);
INSERT INTO "annotation" VALUES(14,'KOKOM','key','KOKOM ','Comparison Particle',NULL);
INSERT INTO "annotation" VALUES(15,'KON','key','KON ','Coordinating Conjuncion',NULL);
INSERT INTO "annotation" VALUES(16,'KOUI','key','KOUI ','Subordinating Conjunction with ''zu''',NULL);
INSERT INTO "annotation" VALUES(17,'KOUS','key','KOUS ','Subordinating Conjunction with Sentence',NULL);
INSERT INTO "annotation" VALUES(18,'NE','key','NE ','Named Entity',NULL);
INSERT INTO "annotation" VALUES(19,'NN','key','NN ','Normal Nomina',NULL);
INSERT INTO "annotation" VALUES(20,'PAV','key','PAV ','Pronominal Adverb',NULL);
INSERT INTO "annotation" VALUES(21,'PDAT','key','PDAT ','Attributive Demonstrative Pronoun',NULL);
INSERT INTO "annotation" VALUES(22,'PDS','key','PDS ','Substitutive Demonstrative Pronoun',NULL);
INSERT INTO "annotation" VALUES(23,'PIAT','key','PIAT ','Attributive Indefinite Pronoun without Determiner',NULL);
INSERT INTO "annotation" VALUES(24,'PIDAT','key','PIDAT ','Attributive Indefinite Pronoun with Determiner',NULL);
INSERT INTO "annotation" VALUES(25,'PIS','key','PIS ','Substitutive Indefinite Pronoun',NULL);
INSERT INTO "annotation" VALUES(26,'PPER','key','PPER ','Personal Pronoun',NULL);
INSERT INTO "annotation" VALUES(27,'PPOSAT','key','PPOSAT ','Attributive Possessive Pronoun',NULL);
INSERT INTO "annotation" VALUES(28,'PPOSS','key','PPOSS ','Substitutive Possessive Pronoun',NULL);
INSERT INTO "annotation" VALUES(29,'PRELAT','key','PRELAT ','Attributive Relative Pronoun',NULL);
INSERT INTO "annotation" VALUES(30,'PRELS','key','PRELS ','Substitutive Relative Pronoun',NULL);
INSERT INTO "annotation" VALUES(31,'PRF','key','PRF ','Reflexive Pronoun',NULL);
INSERT INTO "annotation" VALUES(32,'PROAV','key','PROAV ','Pronominal Adverb',NULL);
INSERT INTO "annotation" VALUES(33,'PTKA','key','PTKA ','Particle with Adjective',NULL);
INSERT INTO "annotation" VALUES(34,'PTKANT','key','PTKANT ','Answering Particle',NULL);
INSERT INTO "annotation" VALUES(35,'PTKNEG','key','PTKNEG ','Negation Particle',NULL);
INSERT INTO "annotation" VALUES(36,'PTKVZ','key','PTKVZ ','Separated Verbal Particle',NULL);
INSERT INTO "annotation" VALUES(37,'PTKZU','key','PTKZU ','''zu'' Particle',NULL);
INSERT INTO "annotation" VALUES(38,'PWAT','key','PWAT ','Attributive Interrogative Pronoun',NULL);
INSERT INTO "annotation" VALUES(39,'PWAV','key','PWAV ','Adverbial Interrogative Pronoun',NULL);
INSERT INTO "annotation" VALUES(40,'PWS','key','PWS ','Substitutive Interrogative Pronoun',NULL);
INSERT INTO "annotation" VALUES(41,'TRUNC','key','TRUNC ','Truncated',NULL);
INSERT INTO "annotation" VALUES(42,'VAFIN','key','VAFIN ','Auxiliary Finite Verb',NULL);
INSERT INTO "annotation" VALUES(43,'VAIMP','key','VAIMP ','Auxiliary Finite Imperative Verb',NULL);
INSERT INTO "annotation" VALUES(44,'VAINF','key','VAINF ','Auxiliary Infinite Verb',NULL);
INSERT INTO "annotation" VALUES(45,'VAPP','key','VAPP ','Auxiliary Perfect Participle',NULL);
INSERT INTO "annotation" VALUES(46,'VMFIN','key','VMFIN ','Modal Finite Verb',NULL);
INSERT INTO "annotation" VALUES(47,'VMINF','key','VMINF ','Modal Infinite Verb',NULL);
INSERT INTO "annotation" VALUES(48,'VMPP','key','VMPP ','Modal Perfect Participle',NULL);
INSERT INTO "annotation" VALUES(49,'VVFIN','key','VVFIN ','Finite Verb',NULL);
INSERT INTO "annotation" VALUES(50,'VVIMP','key','VVIMP ','Finite Imperative Verb',NULL);
INSERT INTO "annotation" VALUES(51,'VVINF','key','VVINF ','Infinite Verb',NULL);
INSERT INTO "annotation" VALUES(52,'VVIZU','key','VVIZU ','Infinite Verb with ''zu''',NULL);
INSERT INTO "annotation" VALUES(53,'VVPP','key','VVPP ','Perfect Participle',NULL);
INSERT INTO "annotation" VALUES(54,'XY','key','XY ','Non-Word',NULL);
INSERT INTO "annotation" VALUES(55,'mate','foundry',NULL,'Mate',NULL);
INSERT INTO "annotation" VALUES(56,'l','layer',NULL,'Lemma',NULL);
INSERT INTO "annotation" VALUES(57,'m','layer',NULL,'Morphology',NULL);
INSERT INTO "annotation" VALUES(58,'<root-POS>','key','<root-POS>','Root Part of Speech',NULL);
INSERT INTO "annotation" VALUES(59,'case','key',NULL,'Case',NULL);
INSERT INTO "annotation" VALUES(60,'degree','key',NULL,'Degree',NULL);
INSERT INTO "annotation" VALUES(61,'gender','key',NULL,'Gender',NULL);
INSERT INTO "annotation" VALUES(62,'mood','key',NULL,'Mood',NULL);
INSERT INTO "annotation" VALUES(63,'number','key',NULL,'Number',NULL);
INSERT INTO "annotation" VALUES(64,'person','key',NULL,'Person',NULL);
INSERT INTO "annotation" VALUES(65,'tense','key',NULL,'Tense',NULL);
INSERT INTO "annotation" VALUES(66,'<no-type> ','key',NULL,'No type',NULL);
INSERT INTO "annotation" VALUES(67,'acc','value','acc ','Accusative',NULL);
INSERT INTO "annotation" VALUES(68,'dat','value','dat ','Dative',NULL);
INSERT INTO "annotation" VALUES(69,'gen','value','gen ','Genitive',NULL);
INSERT INTO "annotation" VALUES(70,'nom','value','nom ','Nominative',NULL);
INSERT INTO "annotation" VALUES(71,'*','value','* ','Undefined',NULL);
INSERT INTO "annotation" VALUES(72,'comp','value','comp ','Comparative',NULL);
INSERT INTO "annotation" VALUES(73,'pos','value','pos ','Positive',NULL);
INSERT INTO "annotation" VALUES(74,'sup','value','sup ','Superative',NULL);
INSERT INTO "annotation" VALUES(75,'fem','value','fem ','Feminium',NULL);
INSERT INTO "annotation" VALUES(76,'masc','value','masc ','Masculinum',NULL);
INSERT INTO "annotation" VALUES(77,'neut','value','neut ','Neuter',NULL);
INSERT INTO "annotation" VALUES(78,'imp','value','imp ','Imperative',NULL);
INSERT INTO "annotation" VALUES(79,'ind','value','ind ','Indicative',NULL);
INSERT INTO "annotation" VALUES(80,'subj','value','subj ','Subjunctive',NULL);
INSERT INTO "annotation" VALUES(81,'pl','value','pl ','Plural',NULL);
INSERT INTO "annotation" VALUES(82,'sg','value','sg ','Singular',NULL);
INSERT INTO "annotation" VALUES(83,'1','value','1 ','First Person',NULL);
INSERT INTO "annotation" VALUES(84,'2','value','2 ','Second Person',NULL);
INSERT INTO "annotation" VALUES(85,'3','value','3 ','Third Person',NULL);
INSERT INTO "annotation" VALUES(86,'past','value','past ','Past',NULL);
INSERT INTO "annotation" VALUES(87,'pres','value','pres ','Present',NULL);
INSERT INTO "annotation" VALUES(88,'malt','foundry',NULL,'Malt',NULL);
INSERT INTO "annotation" VALUES(89,'d','layer',NULL,'Dependency',NULL);
INSERT INTO "annotation" VALUES(90,'-PUNCT-','key','-PUNCT- ','',NULL);
INSERT INTO "annotation" VALUES(91,'-UNKNOWN-','key','-UNKNOWN- ','',NULL);
INSERT INTO "annotation" VALUES(92,'APP','key','APP ','',NULL);
INSERT INTO "annotation" VALUES(93,'ATTR','key','ATTR ','',NULL);
INSERT INTO "annotation" VALUES(94,'AUX','key','AUX ','',NULL);
INSERT INTO "annotation" VALUES(95,'AVZ','key','AVZ ','',NULL);
INSERT INTO "annotation" VALUES(96,'CJ','key','CJ ','',NULL);
INSERT INTO "annotation" VALUES(97,'DET','key','DET ','',NULL);
INSERT INTO "annotation" VALUES(98,'EXPL','key','EXPL ','',NULL);
INSERT INTO "annotation" VALUES(99,'GMOD','key','GMOD ','',NULL);
INSERT INTO "annotation" VALUES(100,'GRAD','key','GRAD ','',NULL);
INSERT INTO "annotation" VALUES(101,'KOM','key','KOM ','',NULL);
INSERT INTO "annotation" VALUES(102,'KONJ','key','KONJ ','',NULL);
INSERT INTO "annotation" VALUES(103,'NEB','key','NEB ','',NULL);
INSERT INTO "annotation" VALUES(104,'OBJA','key','OBJA ','',NULL);
INSERT INTO "annotation" VALUES(105,'OBJC','key','OBJC ','',NULL);
INSERT INTO "annotation" VALUES(106,'OBJD','key','OBJD ','',NULL);
INSERT INTO "annotation" VALUES(107,'OBJG','key','OBJG ','',NULL);
INSERT INTO "annotation" VALUES(108,'OBJI','key','OBJI ','',NULL);
INSERT INTO "annotation" VALUES(109,'OBJP','key','OBJP ','',NULL);
INSERT INTO "annotation" VALUES(110,'PAR','key','PAR ','',NULL);
INSERT INTO "annotation" VALUES(111,'PART','key','PART ','',NULL);
INSERT INTO "annotation" VALUES(112,'PN','key','PN ','',NULL);
INSERT INTO "annotation" VALUES(113,'PP','key','PP ','',NULL);
INSERT INTO "annotation" VALUES(114,'PRED','key','PRED ','',NULL);
INSERT INTO "annotation" VALUES(115,'REL','key','REL ','',NULL);
INSERT INTO "annotation" VALUES(116,'ROOT','key','ROOT ','',NULL);
INSERT INTO "annotation" VALUES(117,'S','key','S ','',NULL);
INSERT INTO "annotation" VALUES(118,'SUBJ','key','SUBJ ','',NULL);
INSERT INTO "annotation" VALUES(119,'SUBJC','key','SUBJC ','',NULL);
INSERT INTO "annotation" VALUES(120,'ZEIT','key','ZEIT ','',NULL);
INSERT INTO "annotation" VALUES(121,'gmod-app','key','gmod-app ','',NULL);
INSERT INTO "annotation" VALUES(122,'koord','key','koord ','',NULL);
INSERT INTO "annotation" VALUES(123,'drukola','foundry',NULL,'DRuKoLa',NULL);
INSERT INTO "annotation" VALUES(124,'ctag','key',NULL,'CTAG',NULL);
INSERT INTO "annotation" VALUES(125,'A','value','a ','Adjective',NULL);
INSERT INTO "annotation" VALUES(126,'Y','value','y ','Abbreviation',NULL);
INSERT INTO "annotation" VALUES(127,'AN','value','an ','Adjective, Indefinite',NULL);
INSERT INTO "annotation" VALUES(128,'APRY','value','apry ','Adjective, Plural, Direct, Definite',NULL);
INSERT INTO "annotation" VALUES(129,'APN','value','apn ','Adjective, Plural, Indefinite',NULL);
INSERT INTO "annotation" VALUES(130,'APOY','value','apoy ','Adjective, Plural, Oblique, Definite',NULL);
INSERT INTO "annotation" VALUES(131,'APON','value','apon ','Adjective, Plural, Oblique, Indefinite',NULL);
INSERT INTO "annotation" VALUES(132,'ASRY','value','asry ','Adjective, Singular, Direct, Definite',NULL);
INSERT INTO "annotation" VALUES(133,'ASN','value','asn ','Adjective, Singular, Indefinite',NULL);
INSERT INTO "annotation" VALUES(134,'ASOY','value','asoy ','Adjective, Singular, Oblique, Definite',NULL);
INSERT INTO "annotation" VALUES(135,'ASON','value','ason ','Adjective, Singular, Oblique, Indefinite',NULL);
INSERT INTO "annotation" VALUES(136,'ASVY','value','asvy ','Adjective, Singular, Vocative, Definite',NULL);
INSERT INTO "annotation" VALUES(137,'ASVN','value','asvn ','Adjective, Singular, Vocative, Indefinite',NULL);
INSERT INTO "annotation" VALUES(138,'R','value','r ','Adverb',NULL);
INSERT INTO "annotation" VALUES(139,'RC','value','rc ','Adverb, Portmanteau',NULL);
INSERT INTO "annotation" VALUES(140,'TS','value','ts ','Article, Definite or Possessive, Singular',NULL);
INSERT INTO "annotation" VALUES(141,'TP','value','tp ','Article, Indefinite or Possessive, Plural',NULL);
INSERT INTO "annotation" VALUES(142,'TPR','value','tpr ','Article, non-Possessive, Plural, Direct',NULL);
INSERT INTO "annotation" VALUES(143,'TPO','value','tpo ','Article, non-Possessive, Plural, Oblique',NULL);
INSERT INTO "annotation" VALUES(144,'TSR','value','tsr ','Article, non-Possessive, Singular, Direct',NULL);
INSERT INTO "annotation" VALUES(145,'TSO','value','tso ','Article, non-Possessive, Singular, Oblique',NULL);
INSERT INTO "annotation" VALUES(146,'NPRY','value','npry ','Common Noun, Plural, Direct, Definite',NULL);
INSERT INTO "annotation" VALUES(147,'NPN','value','npn ','Common Noun, Plural, Indefinite',NULL);
INSERT INTO "annotation" VALUES(148,'NPOY','value','npoy ','Common Noun, Plural, Oblique, Definite',NULL);
INSERT INTO "annotation" VALUES(149,'NPVY','value','npvy ','Common Noun, Plural, Vocative, Definite',NULL);
INSERT INTO "annotation" VALUES(150,'NN','value','nn ','Common Noun, singular',NULL);
INSERT INTO "annotation" VALUES(151,'NSY','value','nsy ','Common Noun, Singular, Definite',NULL);
INSERT INTO "annotation" VALUES(152,'NSRY','value','nsry ','Common Noun, Singular, Direct, Definite',NULL);
INSERT INTO "annotation" VALUES(153,'NSRN','value','nsrn ','Common Noun, Singular, Direct, Indefinite',NULL);
INSERT INTO "annotation" VALUES(154,'NSN','value','nsn ','Common Noun, Singular, Indefinite',NULL);
INSERT INTO "annotation" VALUES(155,'NSOY','value','nsoy ','Common Noun, Singular, Oblique, Definite',NULL);
INSERT INTO "annotation" VALUES(156,'NSON','value','nson ','Common Noun, Singular, Oblique, Indefinite',NULL);
INSERT INTO "annotation" VALUES(157,'NSVY','value','nsvy ','Common Noun, Singular, Vocative, Definite',NULL);
INSERT INTO "annotation" VALUES(158,'NSVN','value','nsvn ','Common Noun, Singular, Vocative, Indefinite',NULL);
INSERT INTO "annotation" VALUES(159,'CR','value','cr ','Conjunctio, portmanteau',NULL);
INSERT INTO "annotation" VALUES(160,'C','value','c ','Conjunction',NULL);
INSERT INTO "annotation" VALUES(161,'QF','value','qf ','Future Particle',NULL);
INSERT INTO "annotation" VALUES(162,'QN','value','qn ','Infinitival Particle',NULL);
INSERT INTO "annotation" VALUES(163,'I','value','i ','Interjection',NULL);
INSERT INTO "annotation" VALUES(164,'QZ','value','qz ','Negative Particle',NULL);
INSERT INTO "annotation" VALUES(165,'M','value','m ','Numeral',NULL);
INSERT INTO "annotation" VALUES(166,'PP','value','pp ','Personal Pronoun',NULL);
INSERT INTO "annotation" VALUES(167,'PPP','value','ppp ','Personal Pronoun, Plural',NULL);
INSERT INTO "annotation" VALUES(168,'PPPA','value','pppa ','Personal Pronoun, Plural, Acc.',NULL);
INSERT INTO "annotation" VALUES(169,'PPPD','value','pppd ','Personal Pronoun, Plural, Dative',NULL);
INSERT INTO "annotation" VALUES(170,'PPPR','value','pppr ','Personal Pronoun, Plural, Direct',NULL);
INSERT INTO "annotation" VALUES(171,'PPPO','value','pppo ','Personal Pronoun, Plural, Oblique',NULL);
INSERT INTO "annotation" VALUES(172,'PPS','value','pps ','Personal Pronoun, Singular',NULL);
INSERT INTO "annotation" VALUES(173,'PPSA','value','ppsa ','Personal Pronoun, Singular, Accusative',NULL);
INSERT INTO "annotation" VALUES(174,'PPSD','value','ppsd ','Personal Pronoun, Singular, Dative',NULL);
INSERT INTO "annotation" VALUES(175,'PPSR','value','ppsr ','Personal Pronoun, Singular, Direct',NULL);
INSERT INTO "annotation" VALUES(176,'PPSN','value','ppsn ','Personal Pronoun, Singular, Nominative',NULL);
INSERT INTO "annotation" VALUES(177,'PPSO','value','ppso ','Personal Pronoun, Singular, Oblique',NULL);
INSERT INTO "annotation" VALUES(178,'S','value','s ','Preposition',NULL);
INSERT INTO "annotation" VALUES(179,'DMPR','value','dmpr ','Pronoun or Determiner, Demonstrative, Plural, Direct',NULL);
INSERT INTO "annotation" VALUES(180,'DMPO','value','dmpo ','Pronoun or Determiner, Demonstrative, Plural, Oblique',NULL);
INSERT INTO "annotation" VALUES(181,'DMSR','value','dmsr ','Pronoun or Determiner, Demonstrative, Singular, Direct',NULL);
INSERT INTO "annotation" VALUES(182,'DMSO','value','dmso ','Pronoun or Determiner, Demonstrative, Singular, Oblique',NULL);
INSERT INTO "annotation" VALUES(183,'PS','value','ps ','Pronoun or Determiner, Poss or Emph',NULL);
INSERT INTO "annotation" VALUES(184,'PSS','value','pss ','Pronoun or Determiner, Poss or Emph, Singular',NULL);
INSERT INTO "annotation" VALUES(185,'RELR','value','relr ','Pronoun or Determiner, Relative, Direct',NULL);
INSERT INTO "annotation" VALUES(186,'RELO','value','relo ','Pronoun or Determiner, Relative, Oblique',NULL);
INSERT INTO "annotation" VALUES(187,'NP','value','np ','Proper Noun',NULL);
INSERT INTO "annotation" VALUES(188,'PI','value','pi ','Quantifier Pronoun or Determiner',NULL);
INSERT INTO "annotation" VALUES(189,'PXA','value','pxa ','Reflexive Pronoun, Accusative',NULL);
INSERT INTO "annotation" VALUES(190,'PXD','value','pxd ','Reflexive Pronoun, Dative',NULL);
INSERT INTO "annotation" VALUES(191,'X','value','x ','Residual',NULL);
INSERT INTO "annotation" VALUES(192,'QS','value','qs ','Subjunctive Particle',NULL);
INSERT INTO "annotation" VALUES(193,'VA','value','va ','Verb, Auxiliary',NULL);
INSERT INTO "annotation" VALUES(194,'VA1','value','va1 ','Verb, Auxiliary, 1st person',NULL);
INSERT INTO "annotation" VALUES(195,'VA2P','value','va2p ','Verb, Auxiliary, 2nd person, Plural',NULL);
INSERT INTO "annotation" VALUES(196,'VA2S','value','va2s ','Verb, Auxiliary, 2nd person, Singular',NULL);
INSERT INTO "annotation" VALUES(197,'VA3','value','va3 ','Verb, Auxiliary, 3rd person',NULL);
INSERT INTO "annotation" VALUES(198,'VA3P','value','va3p ','Verb, Auxiliary, 3rd person, Plural',NULL);
INSERT INTO "annotation" VALUES(199,'VA3S','value','va3s ','Verb, Auxiliary, 3rd person, Singular',NULL);
INSERT INTO "annotation" VALUES(200,'VA1P','value','va1p ','Verb, Auxiliary,1st person, Plural',NULL);
INSERT INTO "annotation" VALUES(201,'VA1S','value','va1s ','Verb, Auxiliary,1st person, Singular',NULL);
INSERT INTO "annotation" VALUES(202,'VG','value','vg ','Verb, Gerund',NULL);
INSERT INTO "annotation" VALUES(203,'VN','value','vn ','Verb, Infinitive',NULL);
INSERT INTO "annotation" VALUES(204,'V1','value','v1 ','Verb, Main, 1st person',NULL);
INSERT INTO "annotation" VALUES(205,'V2','value','v2 ','Verb, Main, 2nd person',NULL);
INSERT INTO "annotation" VALUES(206,'V3','value','v3 ','Verb, Main, 3rd person',NULL);
INSERT INTO "annotation" VALUES(207,'VPPF','value','vppf ','Verb, Participle, Plural, Feminine',NULL);
INSERT INTO "annotation" VALUES(208,'VPPM','value','vppm ','Verb, Participle, Plural, Masculine',NULL);
INSERT INTO "annotation" VALUES(209,'VPSF','value','vpsf ','Verb, Participle, Singular, Feminine',NULL);
INSERT INTO "annotation" VALUES(210,'VPSM','value','vpsm ','Verb, Participle, Singular, Masculine',NULL);
INSERT INTO "annotation" VALUES(211,'cnx','foundry',NULL,'Connexor',NULL);
INSERT INTO "annotation" VALUES(212,'c','layer',NULL,'Constituency',NULL);
INSERT INTO "annotation" VALUES(213,'syn','layer',NULL,'Syntax',NULL);
INSERT INTO "annotation" VALUES(214,'np','key','np ','Nominal Phrase',NULL);
INSERT INTO "annotation" VALUES(215,'Abbr','key','Abbr ','Nouns: Abbreviation',NULL);
INSERT INTO "annotation" VALUES(216,'CMP','key','CMP ','Adjective: Comparative',NULL);
INSERT INTO "annotation" VALUES(217,'IMP','key','IMP ','Mood: Imperative',NULL);
INSERT INTO "annotation" VALUES(218,'IND','key','IND ','Mood: Indicative',NULL);
INSERT INTO "annotation" VALUES(219,'INF','key','INF ','Infinitive',NULL);
INSERT INTO "annotation" VALUES(220,'ORD','key','ORD ','Numeral: Ordinal',NULL);
INSERT INTO "annotation" VALUES(221,'PAST','key','PAST ','Tense: past',NULL);
INSERT INTO "annotation" VALUES(222,'PCP','key','PCP ','Participle',NULL);
INSERT INTO "annotation" VALUES(223,'PERF','key','PERF ','Perfective Participle',NULL);
INSERT INTO "annotation" VALUES(224,'PL','key','PL ','Nouns: Plural',NULL);
INSERT INTO "annotation" VALUES(225,'PRES','key','PRES ','Tense: present',NULL);
INSERT INTO "annotation" VALUES(226,'PROG','key','PROG ','Progressive Participle',NULL);
INSERT INTO "annotation" VALUES(227,'Prop','key','Prop ','Nouns: Proper Noun',NULL);
INSERT INTO "annotation" VALUES(228,'SUB','key','SUB ','Mood: Subjunctive',NULL);
INSERT INTO "annotation" VALUES(229,'SUP','key','SUP ','Adjective: Superlative',NULL);
INSERT INTO "annotation" VALUES(230,'A','key','A ','Adjective',NULL);
INSERT INTO "annotation" VALUES(231,'CC','key','CC ','Coordination Marker',NULL);
INSERT INTO "annotation" VALUES(232,'CS','key','CS ','Clause Marker',NULL);
INSERT INTO "annotation" VALUES(233,'INTERJ','key','INTERJ ','Interjection',NULL);
INSERT INTO "annotation" VALUES(234,'N','key','N ','Noun',NULL);
INSERT INTO "annotation" VALUES(235,'NUM','key','NUM ','Numeral',NULL);
INSERT INTO "annotation" VALUES(236,'PREP','key','PREP ','Preposition',NULL);
INSERT INTO "annotation" VALUES(237,'PRON','key','PRON ','Pro-Nominal',NULL);
INSERT INTO "annotation" VALUES(238,'V','key','V ','Verb',NULL);
INSERT INTO "annotation" VALUES(239,'@ADVL','key','@ADVL ','Adverbial Head',NULL);
INSERT INTO "annotation" VALUES(240,'@AUX','key','@AUX ','Auxiliary Verb',NULL);
INSERT INTO "annotation" VALUES(241,'@CC','key','@CC ','Coordination',NULL);
INSERT INTO "annotation" VALUES(242,'@MAIN','key','@MAIN ','Main Verb',NULL);
INSERT INTO "annotation" VALUES(243,'@NH','key','@NH ','Nominal Head',NULL);
INSERT INTO "annotation" VALUES(244,'@POSTMOD','key','@POSTMOD ','Postmodifier',NULL);
INSERT INTO "annotation" VALUES(245,'@PREMARK','key','@PREMARK ','Preposed Marker',NULL);
INSERT INTO "annotation" VALUES(246,'@PREMOD','key','@PREMOD ','Premodifier',NULL);
INSERT INTO "annotation" VALUES(247,'marmot','foundry',NULL,'MarMoT',NULL);
INSERT INTO "annotation" VALUES(248,'base','foundry',NULL,'Base Annotation',NULL);
INSERT INTO "annotation" VALUES(249,'s','layer',NULL,'Structure',NULL);
INSERT INTO "annotation" VALUES(250,'s','key','s','Sentence',NULL);
INSERT INTO "annotation" VALUES(251,'p','key','p','Paragraph',NULL);
INSERT INTO "annotation" VALUES(252,'t','key','t','Text',NULL);
INSERT INTO "annotation" VALUES(253,'xip','foundry',NULL,'Xerox Parser',NULL);
INSERT INTO "annotation" VALUES(254,'lwc','foundry',NULL,'LWC',NULL);
INSERT INTO "annotation" VALUES(255,'AC','key','AC ','adpositional case marker',NULL);
INSERT INTO "annotation" VALUES(256,'ADC','key','ADC ','adjective component',NULL);
INSERT INTO "annotation" VALUES(257,'AMS','key','AMS ','measure argument of adj',NULL);
INSERT INTO "annotation" VALUES(258,'AVC','key','AVC ','adverbial phrase component',NULL);
INSERT INTO "annotation" VALUES(259,'CD','key','CD ','coordinating conjunction',NULL);
INSERT INTO "annotation" VALUES(260,'CM','key','CM ','comparative concjunction',NULL);
INSERT INTO "annotation" VALUES(261,'CP','key','CP ','complementizer',NULL);
INSERT INTO "annotation" VALUES(262,'DA','key','DA ','dative',NULL);
INSERT INTO "annotation" VALUES(263,'DH','key','DH ','discourse-level head',NULL);
INSERT INTO "annotation" VALUES(264,'DM','key','DM ','discourse marker',NULL);
INSERT INTO "annotation" VALUES(265,'GL','key','GL ','prenominal genitive',NULL);
INSERT INTO "annotation" VALUES(266,'GR','key','GR ','postnominal genitive',NULL);
INSERT INTO "annotation" VALUES(267,'HD','key','HD ','head',NULL);
INSERT INTO "annotation" VALUES(268,'JU','key','JU ','junctor',NULL);
INSERT INTO "annotation" VALUES(269,'MC','key','MC ','comitative',NULL);
INSERT INTO "annotation" VALUES(270,'MI','key','MI ','instrumental',NULL);
INSERT INTO "annotation" VALUES(271,'ML','key','ML ','locative',NULL);
INSERT INTO "annotation" VALUES(272,'MNR','key','MNR ','postnominal modifier',NULL);
INSERT INTO "annotation" VALUES(273,'MO','key','MO ','modifier',NULL);
INSERT INTO "annotation" VALUES(274,'MR','key','MR ','rhetorical modifier',NULL);
INSERT INTO "annotation" VALUES(275,'MW','key','MW ','way (directional modifier)',NULL);
INSERT INTO "annotation" VALUES(276,'NG','key','NG ','negation',NULL);
INSERT INTO "annotation" VALUES(277,'NK','key','NK ','noun kernel modifier',NULL);
INSERT INTO "annotation" VALUES(278,'NMC','key','NMC ','numerical component',NULL);
INSERT INTO "annotation" VALUES(279,'OA','key','OA ','accusative object',NULL);
INSERT INTO "annotation" VALUES(280,'OA2','key','OA2 ','second accusative object',NULL);
INSERT INTO "annotation" VALUES(281,'OC','key','OC ','clausal object',NULL);
INSERT INTO "annotation" VALUES(282,'OG','key','OG ','genitive object',NULL);
INSERT INTO "annotation" VALUES(283,'PD','key','PD ','predicate',NULL);
INSERT INTO "annotation" VALUES(284,'PG','key','PG ','pseudo-genitive',NULL);
INSERT INTO "annotation" VALUES(285,'PH','key','PH ','placeholder',NULL);
INSERT INTO "annotation" VALUES(286,'PM','key','PM ','morphological particle',NULL);
INSERT INTO "annotation" VALUES(287,'PNC','key','PNC ','proper noun component',NULL);
INSERT INTO "annotation" VALUES(288,'RC','key','RC ','relative clause',NULL);
INSERT INTO "annotation" VALUES(289,'RE','key','RE ','repeated element',NULL);
INSERT INTO "annotation" VALUES(290,'RS','key','RS ','reported speech',NULL);
INSERT INTO "annotation" VALUES(291,'SB','key','SB ','subject',NULL);
INSERT INTO "annotation" VALUES(292,'SBP','key','SBP ','passivised subject (PP)',NULL);
INSERT INTO "annotation" VALUES(293,'SP','key','SP ','subject or predicate',NULL);
INSERT INTO "annotation" VALUES(294,'SVP','key','SVP ','separable verb prefix',NULL);
INSERT INTO "annotation" VALUES(295,'UC','key','UC ','(idiosyncratic) unit component',NULL);
INSERT INTO "annotation" VALUES(296,'VO','key','VO ','vocative',NULL);
INSERT INTO "annotation" VALUES(297,'dereko','foundry',NULL,'DeReKo',NULL);
INSERT INTO "annotation" VALUES(298,'sgbr','foundry',NULL,'Schreibgebrauch',NULL);
INSERT INTO "annotation" VALUES(299,'lv','layer',NULL,'Lemma Variants',NULL);
INSERT INTO "annotation" VALUES(300,'NNE','key','NNE','Normal Nomina with Named Entity',NULL);
INSERT INTO "annotation" VALUES(301,'ADVART','key','ADVART','Adverb with Article',NULL);
INSERT INTO "annotation" VALUES(302,'EMOASC','key','EMOASC','ASCII emoticon',NULL);
INSERT INTO "annotation" VALUES(303,'EMOIMG','key','EMOIMG','Graphic emoticon',NULL);
INSERT INTO "annotation" VALUES(304,'ERRTOK','key','ERRTOK','Tokenisation Error',NULL);
INSERT INTO "annotation" VALUES(305,'HST','key','HST','Hashtag',NULL);
INSERT INTO "annotation" VALUES(306,'KOUSPPER','key','KOUSPPER','Subordinating Conjunction (with Sentence) with Personal Pronoun',NULL);
INSERT INTO "annotation" VALUES(307,'ONO','key','ONO','Onomatopoeia',NULL);
INSERT INTO "annotation" VALUES(308,'PPERPPER','key','PPERPPER','Personal Pronoun with Personal Pronoun',NULL);
INSERT INTO "annotation" VALUES(309,'URL','key','URL','Uniform Resource Locator',NULL);
INSERT INTO "annotation" VALUES(310,'VAPPER','key','VAPPER','Finite Auxiliary Verb with Personal Pronoun',NULL);
INSERT INTO "annotation" VALUES(311,'VMPPER','key','VMPPER','Fintite Modal Verb with Personal Pronoun',NULL);
INSERT INTO "annotation" VALUES(312,'VVPPER','key','VVPPER','Finite Full Verb with Personal Pronoun',NULL);
INSERT INTO "annotation" VALUES(313,'AW','key','AW','Interaction Word',NULL);
INSERT INTO "annotation" VALUES(314,'ADR','key','ADR','Addressing Term',NULL);
INSERT INTO "annotation" VALUES(315,'AWIND','key','AWIND','Punctuation Indicating Addressing Term',NULL);
INSERT INTO "annotation" VALUES(316,'ERRAW','key','ERRAW','Part of Erroneously Separated Compound',NULL);
INSERT INTO "annotation" VALUES(317,'corenlp','foundry',NULL,'CoreNLP',NULL);
INSERT INTO "annotation" VALUES(318,'ne','layer',NULL,'Named Entity',NULL);
INSERT INTO "annotation" VALUES(319,'ne_dewac_175m_600','layer',NULL,'Named Entity',NULL);
INSERT INTO "annotation" VALUES(320,'ne_hgc_175m_600','layer',NULL,'Named Entity',NULL);
INSERT INTO "annotation" VALUES(321,'I-LOC','key','I-LOC ','Location',NULL);
INSERT INTO "annotation" VALUES(322,'I-MISC','key','I-MISC ','Miscellaneous',NULL);
INSERT INTO "annotation" VALUES(323,'I-ORG','key','I-ORG ','Organization',NULL);
INSERT INTO "annotation" VALUES(324,'I-PER','key','I-PER ','Person',NULL);
INSERT INTO "annotation" VALUES(325,'AA','key','AA','superlative phrase with ''am''',NULL);
INSERT INTO "annotation" VALUES(326,'AP','key','AP','adjektive phrase',NULL);
INSERT INTO "annotation" VALUES(327,'AVP','key','AVP','adverbial phrase',NULL);
INSERT INTO "annotation" VALUES(328,'CAP','key','CAP','coordinated adjektive phrase',NULL);
INSERT INTO "annotation" VALUES(329,'CAVP','key','CAVP','coordinated adverbial phrase',NULL);
INSERT INTO "annotation" VALUES(330,'CAC','key','CAC','coordinated adposition',NULL);
INSERT INTO "annotation" VALUES(331,'CCP','key','CCP','coordinated complementiser',NULL);
INSERT INTO "annotation" VALUES(332,'CH','key','CH','chunk',NULL);
INSERT INTO "annotation" VALUES(333,'CNP','key','CNP','coordinated noun phrase',NULL);
INSERT INTO "annotation" VALUES(334,'CO','key','CO','coordination',NULL);
INSERT INTO "annotation" VALUES(335,'CPP','key','CPP','coordinated adpositional phrase',NULL);
INSERT INTO "annotation" VALUES(336,'CVP','key','CVP','coordinated verb phrase (non-finite)',NULL);
INSERT INTO "annotation" VALUES(337,'CVZ','key','CVZ','coordinated zu-marked infinitive',NULL);
INSERT INTO "annotation" VALUES(338,'DL','key','DL','discourse level constituent',NULL);
INSERT INTO "annotation" VALUES(339,'ISU','key','ISU','idiosyncratis unit',NULL);
INSERT INTO "annotation" VALUES(340,'MPN','key','MPN','multi-word proper noun',NULL);
INSERT INTO "annotation" VALUES(341,'MTA','key','MTA','multi-token adjective',NULL);
INSERT INTO "annotation" VALUES(342,'NM','key','NM','multi-token number',NULL);
INSERT INTO "annotation" VALUES(343,'NP','key','NP','noun phrase',NULL);
INSERT INTO "annotation" VALUES(344,'QL','key','QL','quasi-languag',NULL);
INSERT INTO "annotation" VALUES(345,'VP','key','VP','verb phrase (non-finite)',NULL);
INSERT INTO "annotation" VALUES(346,'VZ','key','VZ','zu-marked infinitive',NULL);
INSERT INTO "annotation" VALUES(347,'AC','value','AC ','adpositional case marker',NULL);
INSERT INTO "annotation" VALUES(348,'ADC','value','ADC ','adjective component',NULL);
INSERT INTO "annotation" VALUES(349,'AMS','value','AMS ','measure argument of adj',NULL);
INSERT INTO "annotation" VALUES(350,'APP','value','APP ','apposition',NULL);
INSERT INTO "annotation" VALUES(351,'AVC','value','AVC ','adverbial phrase component',NULL);
INSERT INTO "annotation" VALUES(352,'CC','value','CC ','comparative complement',NULL);
INSERT INTO "annotation" VALUES(353,'CD','value','CD ','coordinating conjunction',NULL);
INSERT INTO "annotation" VALUES(354,'CJ','value','CJ ','conjunct',NULL);
INSERT INTO "annotation" VALUES(355,'CM','value','CM ','comparative concjunction',NULL);
INSERT INTO "annotation" VALUES(356,'CP','value','CP ','complementizer',NULL);
INSERT INTO "annotation" VALUES(357,'DA','value','DA ','dative',NULL);
INSERT INTO "annotation" VALUES(358,'DH','value','DH ','discourse-level head',NULL);
INSERT INTO "annotation" VALUES(359,'DM','value','DM ','discourse marker',NULL);
INSERT INTO "annotation" VALUES(360,'GL','value','GL ','prenominal genitive',NULL);
INSERT INTO "annotation" VALUES(361,'GR','value','GR ','postnominal genitive',NULL);
INSERT INTO "annotation" VALUES(362,'HD','value','HD ','head',NULL);
INSERT INTO "annotation" VALUES(363,'JU','value','JU ','junctor',NULL);
INSERT INTO "annotation" VALUES(364,'MC','value','MC ','comitative',NULL);
INSERT INTO "annotation" VALUES(365,'MI','value','MI ','instrumental',NULL);
INSERT INTO "annotation" VALUES(366,'ML','value','ML ','locative',NULL);
INSERT INTO "annotation" VALUES(367,'MNR','value','MNR ','postnominal modifier',NULL);
INSERT INTO "annotation" VALUES(368,'MO','value','MO ','modifier',NULL);
INSERT INTO "annotation" VALUES(369,'MR','value','MR ','rhetorical modifier',NULL);
INSERT INTO "annotation" VALUES(370,'MW','value','MW ','way (directional modifier)',NULL);
INSERT INTO "annotation" VALUES(371,'NG','value','NG ','negation',NULL);
INSERT INTO "annotation" VALUES(372,'NK','value','NK ','noun kernel modifier',NULL);
INSERT INTO "annotation" VALUES(373,'NMC','value','NMC ','numerical component',NULL);
INSERT INTO "annotation" VALUES(374,'OA','value','OA ','accusative object',NULL);
INSERT INTO "annotation" VALUES(375,'OA2','value','OA2 ','second accusative object',NULL);
INSERT INTO "annotation" VALUES(376,'OC','value','OC ','clausal object',NULL);
INSERT INTO "annotation" VALUES(377,'OG','value','OG ','genitive object',NULL);
INSERT INTO "annotation" VALUES(378,'PD','value','PD ','predicate',NULL);
INSERT INTO "annotation" VALUES(379,'PG','value','PG ','pseudo-genitive',NULL);
INSERT INTO "annotation" VALUES(380,'PH','value','PH ','placeholder',NULL);
INSERT INTO "annotation" VALUES(381,'PM','value','PM ','morphological particle',NULL);
INSERT INTO "annotation" VALUES(382,'PNC','value','PNC ','proper noun component',NULL);
INSERT INTO "annotation" VALUES(383,'RE','value','RE ','repeated element',NULL);
INSERT INTO "annotation" VALUES(384,'RS','value','RS ','reported speech',NULL);
INSERT INTO "annotation" VALUES(385,'SB','value','SB ','subject',NULL);
INSERT INTO "annotation" VALUES(386,'SBP','value','SBP ','passivised subject (PP)',NULL);
INSERT INTO "annotation" VALUES(387,'SP','value','SP ','subject or predicate',NULL);
INSERT INTO "annotation" VALUES(388,'SVP','value','SVP ','separable verb prefix',NULL);
INSERT INTO "annotation" VALUES(389,'UC','value','UC ','(idiosyncratic) unit component',NULL);
INSERT INTO "annotation" VALUES(390,'VO','value','VO ','vocative',NULL);
INSERT INTO "annotation" VALUES(391,'tt','foundry',NULL,'TreeTagger',NULL);
