ALTER TABLE resource 
ADD COLUMN institution VARCHAR(100) DEFAULT NULL;

ALTER TABLE resource 
ADD COLUMN corpus_query VARCHAR(500) DEFAULT NULL;

ALTER TABLE resource 
ADD COLUMN pid VARCHAR(500) DEFAULT NULL;