name: CI Test

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Kustvakt
        uses: actions/checkout@v2
        with:
          path: Kustvakt

      - name: Checkout Krill
        uses: actions/checkout@v2
        with:
          repository: KorAP/Krill
          path: Krill

      - name: Checkout Koral
        uses: actions/checkout@v2
        with:
          repository: KorAP/Koral
          path: Koral

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build and install Krill
        run: mvn --file Krill/pom.xml install

      - name: Build and install Koral
        run: mvn --file Koral/pom.xml install

	  - name: Build and package Kustvakt full
        run: mvn clean --file Kustvakt/full/pom.xml package 
        
      - name: Build and package Kustvakt lite
        run: mvn clean --file Kustvakt/full/pom.xml package -P lite -DskipTests=true     
